// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kiqsrzkkraxqfyjqnifa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpcXNyemtrcmF4cWZ5anFuaWZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMzE0NTgsImV4cCI6MjA2MTkwNzQ1OH0.2uq4b_tl72Hexl5YfQ0OQSenU2gURZyD79vESFKVjNo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);